// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvHZozzCwrE5PtDUjuZ7iOmtouynzLWD0',
    appId: '1:712653502070:web:1077223f978bf270b5d157',
    messagingSenderId: '712653502070',
    projectId: 'notsoalone-13109',
    authDomain: 'notsoalone-13109.firebaseapp.com',
    storageBucket: 'notsoalone-13109.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbGm-5B4xuwD7xM-FUBUxFOiV4IbWLDQQ',
    appId: '1:712653502070:android:671c16d1751783f8b5d157',
    messagingSenderId: '712653502070',
    projectId: 'notsoalone-13109',
    storageBucket: 'notsoalone-13109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0UrjRPMeARsmbtEATrihmRzrQg6nmcpo',
    appId: '1:712653502070:ios:2a83ccb94d7cb9d7b5d157',
    messagingSenderId: '712653502070',
    projectId: 'notsoalone-13109',
    storageBucket: 'notsoalone-13109.firebasestorage.app',
    iosBundleId: 'com.example.notsoalone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0UrjRPMeARsmbtEATrihmRzrQg6nmcpo',
    appId: '1:712653502070:ios:2a83ccb94d7cb9d7b5d157',
    messagingSenderId: '712653502070',
    projectId: 'notsoalone-13109',
    storageBucket: 'notsoalone-13109.firebasestorage.app',
    iosBundleId: 'com.example.notsoalone2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvHZozzCwrE5PtDUjuZ7iOmtouynzLWD0',
    appId: '1:712653502070:web:f52efb13096fa50cb5d157',
    messagingSenderId: '712653502070',
    projectId: 'notsoalone-13109',
    authDomain: 'notsoalone-13109.firebaseapp.com',
    storageBucket: 'notsoalone-13109.firebasestorage.app',
  );
}
